adb uninstall --user 0 com.sonymobile.entrance
adb uninstall --user 0 com.sonymobile.home
adb uninstall --user 0 com.sonymobile.pobox
adb uninstall --user 0 com.touchtype.swiftkey
adb uninstall --user 0 com.sonyericsson.xhs
adb uninstall --user 0 com.google.android.ims
adb uninstall --user 0 com.google.android.apps.docs.editors.sheets
adb uninstall --user 0 com.google.android.apps.docs.editors.slides
adb uninstall --user 0 com.google.android.apps.docs.editors.docs
adb uninstall --user 0 com.google.android.videos
adb uninstall --user 0 com.google.android.apps.maps
adb uninstall --user 0 com.google.android.calendar 
adb uninstall --user 0 com.s.antivirus
adb uninstall --user 0 com.google.android.apps.tachyon
adb uninstall --user 0 com.facebook.system
adb uninstall --user 0 com.facebook.appmanager
adb uninstall --user 0 com.facebook.services
adb uninstall --user 0 com.sony.nfx.app.sfrc
adb uninstall --user 0 com.sonymobile.xperialounge.services
adb uninstall --user 0 com.amazon.mShop.android.shopping
adb uninstall --user 0 com.sonymobile.lifelog
